# -*- coding: utf-8 -*-
"""task1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TDDMcsD02ApCfMLUvYZi_lVGg2dCnqEv
"""

from transformers import pipeline

# Load the model
classifier = pipeline('sentiment-analysis', model='distilbert-base-uncased-finetuned-sst-2-english')

# Sample text for sentiment analysis
text = "The restaurant was amazing and the food was delicious."
text_2 = "We were late and had a bad experience"

# Apply the model
result = classifier(text)
result_2 = classifier(text_2)

# Display the result
print(result)
print(result_2)
